# Generated by Django 5.1.4 on 2025-09-27 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavedQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sparql_query",
                    models.TextField(
                        help_text="The full text of the query that was saved.",
                        verbose_name="SPARQL Query",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="A descriptive name for the saved query (optional).",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Saved SPARQL Query",
                "verbose_name_plural": "Saved SPARQL Queries",
                "ordering": ["-created_at"],
            },
        ),
    ]
