# Generated by Django 5.1.4 on 2025-09-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="savedquery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Saved Query",
                "verbose_name_plural": "Saved Queries",
            },
        ),
        migrations.RemoveField(
            model_name="savedquery",
            name="name",
        ),
        migrations.RemoveField(
            model_name="savedquery",
            name="sparql_query",
        ),
        migrations.AddField(
            model_name="savedquery",
            name="query",
            field=models.TextField(
                default="", help_text="The full SPARQL query string."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedquery",
            name="title",
            field=models.CharField(
                default="",
                help_text="A descriptive title for the saved query.",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="savedquery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
