# Updated environment.yml - Optimized for Python 3.12.9 compatibility and stability
# Wikidata Explorer Project - Post-Architectural Refactor
# Target Environment: Python 3.12.9 with latest compatible stable versions

name: wikidata-explorer
channels:
  - conda-forge
  - defaults

dependencies:
  # Core Python Environment (FIXED VERSION)
  - python=3.12.9
  
  # Web Framework - Django 5.1 LTS (latest stable with Python 3.12 support)
  - django=5.1.4
  
  # Database - Latest PyMongo for MongoDB (djongo REMOVED)
  - pymongo=4.10.1  # Latest stable with Python 3.12 support
  
  # SPARQL and RDF Libraries - Latest stable versions
  - sparqlwrapper=2.0.0  # Latest stable, well-maintained
  - rdflib=7.1.1         # Updated for better performance and compatibility
  
  # HTTP and Network Libraries - Latest compatible versions
  - requests=2.32.3      # Latest stable with security fixes
  - urllib3=2.2.3        # Compatible with requests 2.32.3
  
  # Data Processing - Latest stable versions for Python 3.12
  - pandas=2.2.3         # Latest stable with Python 3.12 optimizations
  - numpy=2.1.3          # Latest stable, significant performance improvements
  
  # Development and Testing - Latest versions
  - pytest=8.3.4         # Latest stable with improved fixtures
  - pytest-django=4.9.0  # Updated for Django 5.x compatibility  
  - pytest-cov=6.0.0     # Latest with better reporting
  
  # Logging and Monitoring - Updated versions
  - python-json-logger=3.2.1  # Latest stable with structured logging
  
  # Security and Environment - Latest secure versions
  - python-dotenv=1.0.1   # Latest stable
  - cryptography=43.0.3   # Latest with security patches
  
  # Development Tools - Latest formatter/linter versions
  - black=24.10.0         # Latest stable formatter
  - flake8=7.1.1          # Latest linter with Python 3.12 support
  - isort=5.13.2          # Latest import sorter
  - mypy=1.13.0           # Type checking for better code quality
  
  # pip dependencies - Latest versions
  - pip=24.3.1
  - pip:
    # Django ecosystem
    - django-cors-headers==4.6.0     # Latest CORS handling
    - django-extensions==3.2.3       # Useful Django extensions
    
    # Production deployment
    - gunicorn==23.0.0               # Latest WSGI server
    - whitenoise==6.8.2              # Static file serving
    
    # Monitoring and logging
    - sentry-sdk[django]==2.18.0     # Error tracking (optional)
    
    # Performance
    - django-redis==5.4.0            # Redis caching backend (optional)

# Environment Variables (for reference)
variables:
  DJANGO_SETTINGS_MODULE: "explorer.settings"
  PYTHONPATH: "."
  
# Compatibility and Performance Notes:
# 1. Django 5.1.4: Latest stable with official Python 3.12.9 support
# 2. PyMongo 4.10.1: Latest stable with improved connection pooling
# 3. NumPy 2.1.3: Significant performance improvements for Python 3.12
# 4. All packages verified compatible with Python 3.12.9
# 5. Focused on LTS and stable releases for production reliability
# 6. Security patches included in all major dependencies
# 7. Development tools updated for modern Python features